Initially, my message_info files were in the incorrect 
location so there were complications in running the bot. 
I didn't order the commands in the message_info.py 
file properly.
